// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatsNow.Models;

namespace StatsNow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200220165449_TeamAndPlayer")]
    partial class TeamAndPlayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StatsNow.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "SuperLeague"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Junior"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "u20"
                        });
                });

            modelBuilder.Entity("StatsNow.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Away")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamTeamId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("FG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FGA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FGperC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Home")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGamesOfTheSeason")
                        .HasColumnType("bit");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Win")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamTeamId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HomeTeamTeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Away = "Maree",
                            AwayScore = 70,
                            CategoryId = 1,
                            FG = 21m,
                            FGA = 64m,
                            FGperC = 33m,
                            Home = "Moycullen",
                            HomeScore = 58,
                            IsGamesOfTheSeason = false,
                            Venue = "Kingfisher",
                            Win = "No"
                        },
                        new
                        {
                            GameId = 2,
                            Away = "Moycullen",
                            AwayScore = 59,
                            CategoryId = 1,
                            FG = 18m,
                            FGA = 60m,
                            FGperC = 30m,
                            Home = "Killester",
                            HomeScore = 57,
                            IsGamesOfTheSeason = true,
                            Venue = "IWA",
                            Win = "Yes"
                        },
                        new
                        {
                            GameId = 3,
                            Away = "DCU",
                            AwayScore = 87,
                            CategoryId = 1,
                            FG = 22m,
                            FGA = 62m,
                            FGperC = 35m,
                            Home = "Moycullen",
                            HomeScore = 64,
                            IsGamesOfTheSeason = false,
                            Venue = "Kingfisher",
                            Win = "No"
                        },
                        new
                        {
                            GameId = 4,
                            Away = "Moycullen",
                            AwayScore = 73,
                            CategoryId = 1,
                            FG = 28m,
                            FGA = 70m,
                            FGperC = 40m,
                            Home = "UCD",
                            HomeScore = 79,
                            IsGamesOfTheSeason = true,
                            Venue = "UCD",
                            Win = "No"
                        });
                });

            modelBuilder.Entity("StatsNow.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TeamNameTeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeamNameTeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FName = "Ger",
                            LName = "Lyons",
                            PlayerNumber = 7
                        });
                });

            modelBuilder.Entity("StatsNow.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            TeamName = "Moycullen"
                        },
                        new
                        {
                            TeamId = 2,
                            TeamName = "Maree"
                        });
                });

            modelBuilder.Entity("StatsNow.Models.Game", b =>
                {
                    b.HasOne("StatsNow.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamTeamId");

                    b.HasOne("StatsNow.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatsNow.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamTeamId");
                });

            modelBuilder.Entity("StatsNow.Models.Player", b =>
                {
                    b.HasOne("StatsNow.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("StatsNow.Models.Team", "TeamName")
                        .WithMany("Roster")
                        .HasForeignKey("TeamNameTeamId");
                });

            modelBuilder.Entity("StatsNow.Models.Team", b =>
                {
                    b.HasOne("StatsNow.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
